### ISSUE TITLE
Legacy Skyrim

### ISSUE THREAD

**Issue by Vadim000009** [qbx2/sse-mod-hide-remote-desktop#1]
Hello. I saw your modification and was very happy, but unfortunately, it is for SSE. Wouldn't it be difficult to ask to add support for legacy Skyrim as well? 

Thank you in advance for your response

**Comment by qbx2** [comment]
~You could try this: https://www.nexusmods.com/skyrim/mods/50435 , although the use case is a bit different~

**Comment by qbx2** [comment]
I'm sorry, I misunderstood the question. Legacy skyrim is not supported. However it may work with small modifications on SKSE related functions
